import { ZONES, ITEMS, canTravel, isSafeZone, type SaveState, type Zone } from './game/state';
import { JOURNEY, STORY_SITES, MATERIALS, RECIPES, recipeOwned, craftingProblem, journeyRows, type RecipeId, type MaterialId } from './game/journey';
import { icon } from './icons';

export function materialInventory(s: SaveState) {
  return `<div class="modal-section-title">재료와 여정의 도구 <span>사냥 · 조사 · 보급품</span></div><div class="material-grid">${Object.entries(MATERIALS).map(([id, m]) => `<div><span>${m.name}</span><b>${s.materials[id as MaterialId]}</b></div>`).join('')}</div>${s.journey.flags.includes('lantern') ? `<div class="inventory-item"><span class="detail-icon">${icon('sun')}</span><div><b>별빛 등불</b><p>조수륜과 등대 문양을 깨우는 여정의 도구</p></div><span class="tag">보유 중</span></div>` : ''}<p class="modal-footnote">표류목·철·별의 가루는 몬스터 해방과 항구 보급품에서 얻습니다. 조수의 심장은 네리스·아스테르를 처음 해방할 때 얻습니다.</p>`;
}
export function workshopHTML(s: SaveState) {
  return `<p class="dialogue-quote">“좋은 배는 사람을 집으로 데려다주지.<br>내가 만드는 도구도 그러면 좋겠군.”</p><div class="inventory-summary"><span>도란의 작업대</span><b>${icon('coin')} ${s.gold} G</b></div>${materialInventory(s)}<div class="recipe-list">${Object.entries(RECIPES).map(([key, recipe]) => {
    const id = key as RecipeId, owned = recipeOwned(s, id), problem = craftingProblem(s, id);
    return `<article class="recipe-card"><div class="detail-icon">${icon(id === 'lantern' ? 'sun' : ITEMS[id].weapon)}</div><div><h3>${recipe.name}</h3><p>${id === 'lantern' ? recipe.description : ITEMS[id].description}</p><div class="recipe-cost">${Object.entries(recipe.materials).map(([key, amount]) => `<span class="${s.materials[key as MaterialId] < amount ? 'missing' : ''}">${MATERIALS[key as MaterialId].name} ${s.materials[key as MaterialId]} / ${amount}</span>`).join('')}<span>${recipe.gold} G</span></div><button class="secondary-button" data-craft="${id}" ${problem ? 'disabled' : ''}>${owned ? '보유 중' : s.journey.step < recipe.step ? '이야기 진행 후 제작' : '제작하기'}</button>${problem && !owned ? `<small>${problem}</small>` : ''}</div></article>`;
  }).join('')}</div><div class="modal-section-title">부족한 재료 구입 <span>한 번에 1개</span></div><div class="supply-list">${Object.entries(MATERIALS).filter(([, m]) => m.price > 0).map(([id, m]) => `<button class="secondary-button" data-buy-material="${id}" ${s.gold < m.price ? 'disabled' : ''}>${m.name} · ${m.price} G</button>`).join('')}</div>`;
}
export function sideStoryHTML(s: SaveState) {
  return `<section class="side-story"><span class="chapter-label">숲의 선택 이야기</span><h3>약초사의 발자국</h3><p>약초 주머니와 야영지 쪽지를 조사하고, 북쪽의 리라 주변 몬스터를 해방해 구조하세요.</p><div class="objectives">${(['herb', 'camp', 'lyra'] as const).map(id => `<div class="objective ${s.journey.flags.includes(id) ? 'complete' : ''}"><span class="objective-dot">${s.journey.flags.includes(id) ? icon('check') : ''}</span><span>${STORY_SITES[id].name}</span></div>`).join('')}</div><small>${s.journey.flags.includes('lyra') ? '구조 완료 · 리라는 그린헤이븐에 돌아왔습니다.' : '보상: 140 EXP · 90 G · 표류목 2 · 별의 가루 1'}</small></section>`;
}
export function journeyJournalHTML(s: SaveState) {
  const records = s.journey.flags.filter(f => Object.hasOwn(STORY_SITES, f));
  return `${sideStoryHTML(s)}<div class="modal-section-title">검은 조수의 여정 <span>${s.journey.step === 7 ? '완료' : s.journey.step ? '진행 중' : '1막 완료 후 시작'}</span></div><div class="chapter-timeline">${JOURNEY.slice(1).map((q, i) => `<div class="${i + 1 < s.journey.step ? 'done' : i + 1 === s.journey.step ? 'current' : ''}"><span>${i + 1 < s.journey.step ? icon('check') : i + 1}</span><div><small>${q.subtitle}</small><b>${q.title}</b></div></div>`).join('')}</div>${s.journey.runes.length || s.journey.flags.includes('inscription') ? `<p class="help-tip">등대의 순서: 조개 → 달 → 별<br>현재 공명: ${s.journey.runes.length} / 3 · ${s.journey.flags.includes('beacon') ? '등대 복구 완료' : '틀리면 처음부터 다시 작동할 수 있습니다.'}</p>` : ''}<div class="modal-section-title">읽은 기록 <span>언제든 다시 읽을 수 있습니다</span></div><div class="story-records">${records.length ? records.map(id => { const site = STORY_SITES[id as keyof typeof STORY_SITES]; return `<details><summary>${site.name}</summary>${site.text.map(t => `<p>${t}</p>`).join('')}</details>`; }).join('') : '<p class="muted">F로 흔적을 조사하면 여기에 기록됩니다.</p>'}</div>`;
}
export function expansionObjectivesHTML(s: SaveState) {
  if (s.journey.step === 0) return `<div class="objective">${icon('pin')}<span>장로 엘리온에게 다음 이야기 받기</span></div>`;
  if (s.journey.step === 7) return `<div class="objective complete">${icon('check')}<span>돌아온 선원들과 새벽 맞이하기</span></div>`;
  return journeyRows(s).map(row => `<div class="objective ${row.done ? 'complete' : ''}"><span class="objective-dot">${row.done ? icon('check') : ''}</span><span>${row.name}</span><b>${row.done ? '1' : '0'}<em> / 1</em></b></div>`).join('');
}
export function worldMapHTML(s: SaveState) {
  const locations: [number, number, Zone][] = [[75, 100, 'village'], [218, 64, 'forest'], [365, 105, 'plains'], [518, 68, 'depths'], [677, 64, 'sanctum'], [150, 232, 'harbor'], [374, 226, 'wreck'], [606, 235, 'abyss'], [300, 353, 'ruins'], [536, 353, 'roots']];
  return `<p class="modal-intro">숲과 바다를 지나 하늘나무로. 열 곳에 남은 이야기를 찾아가세요.</p><div class="world-map-art"><svg viewBox="0 0 760 425" role="img" aria-label="숲의 다섯 지역과 항구, 난파선, 검은 조수의 제단, 하늘나무와 별의 뿌리 지도"><rect width="760" height="425" fill="#253e34"/><path d="M0 180 Q140 145 300 177 T760 182 V310 H0Z" fill="#375d65"/><path d="M75 100 218 64 365 105 518 68 677 64 M75 100 150 232 374 226 606 235 M75 100 Q80 350 300 353 L536 353" stroke="#c4bd93" stroke-width="2" stroke-dasharray="5 7" fill="none"/>${locations.map(([x,y,id], i) => `<g><circle cx="${x}" cy="${y}" r="${s.zone === id ? 22 : 17}" fill="#22382e" stroke="${canTravel(s,id) ? '#dac48d' : '#738989'}" stroke-width="2"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="#ded3ad" font-size="13">${i+1}</text><text x="${x}" y="${y+38}" text-anchor="middle" fill="#d5d9c8" font-size="11">${ZONES[id].name}</text></g>`).join('')}</svg></div><div class="zone-list">${Object.entries(ZONES).filter(([id]) => id !== 'trial').map(([id, zone]) => {
    const key = id as Zone; const locked = !canTravel(s,key); const unlock = key === 'ruins' ? '2막 후 엘리온과 대화' : key === 'roots' ? '봉인의 운명 선택 후' : key === 'harbor' ? '엘리온의 편지 후' : key === 'wreck' ? '등불 준비 완료 후' : key === 'abyss' ? '등대 복구 후' : `${zone.chapter}장 해금`;
    return `<button data-travel="${key}" class="zone-card ${s.zone === key ? 'current' : ''}" ${locked ? 'disabled' : ''}><div class="zone-number">${icon(locked ? 'lock' : isSafeZone(key) ? 'camp' : 'compass')}</div><div><h3>${zone.name}${key === 'sanctum' && s.chapter >= 5 ? ' · 보스 연습' : ''}</h3><p>Lv. ${zone.level} · ${isSafeZone(key) ? '안전 지역 · 상점과 회복' : zone.creatures.map(c => c === 'starwarden' ? '최후의 수호자' : c === 'thornbeast' ? '가시뿌리 수호수' : c === 'leviathan' ? '심해 수호자' : c === 'reef_shark' ? '암초상어' : c === 'dragon' ? '고대 용' : '저주받은 동물').filter((v,i,a) => a.indexOf(v) === i).join(', ')}</p></div><span>${s.zone === key ? '현재 위치' : locked ? unlock : icon('arrow')}</span></button>`;
  }).join('')}</div>${s.finale.step === 6 ? `<button class="primary-button centered" data-panel="trials">메아리의 회랑 · 도전과 강화 ${icon('arrow')}</button>` : ''}${s.zone === 'trial' ? '<p class="help-tip">다른 지역으로 이동하면 이번 도전과 미수령 보상은 사라집니다.</p>' : ''}<p class="modal-footnote">지도에서 열린 지역을 선택하면 즉시 이동합니다. 첫 이야기를 마치고 엘리온에게 다시 말을 걸면 항구로 가는 길이 열립니다. 난파선의 물길은 현장의 조수륜으로 조절하세요.</p>`;
}
